### PR TITLE
Changed mPanelSlideListeners to a CopyOnWriteArrayList. Addresses #695.

### PR DESCRIPTION
**Pull request by atomjack**

### CODE REVIEW

**Comment by atomjack** [comment]
Is there any chance this could be merged?

**Comment by tokudu** [comment]
I'll merge it this weekend. Sorry for the delay.

**Comment by charlesdurham** [comment]
Should probably also remove the existing synchronization around the panel slide listeners as its no longer necessary.

**Comment by nohe427** [comment]
@tokudu - Any idea on when this may be merged?

**Comment by tokudu** [comment]
Merging.

**Comment by tokudu** [comment]
I'll do another version release soon. Been a bit behind on PR approvals.

**Comment by nohe427** [comment]
Thanks for merging in.  We were running into this defect pretty consistently.  Do you know when you might be pushing out a version update?

Thanks!

**Comment by atomjack** [comment]
Thanks @tokudu!!

**Comment by nohe427** [comment]
Hey @tokudu !

When can we expect 3.3.2 to be released?  We were hoping to have this fix soon.

**Pull request merged**
