### PR TITLE
Take margin top into account for slidable view

### PR DESCRIPTION
**Pull request by thuytrinh**
This PR is for #412.

### CODE REVIEW

**Comment by tokudu** [comment]
Thank you for the contribution. I'd be happy to merge this, but no need to include a new demo. Please remove, and I'll merge. Thanks!

**Comment by thuytrinh** [comment]
@tokudu Yeah, I'm done with removing the new demo.

**Comment by tokudu** [comment]
Also, I see an issue for adding support for left and right margins (https://github.com/umano/AndroidSlidingUpPanel/issues/414). Would you like to add that as well?

**Comment by thuytrinh** [comment]
Yeah, I'm happy to help.

**Pull request merged**
