### PR TITLE
Take marginLeft and marginRight into account for main view

### PR DESCRIPTION
**Pull request by thuytrinh**
This PR is for #414.

device-2015-03-24-222641

### CODE REVIEW

**Comment by tokudu** [comment]
Hi Thuy. This works! Again, no need to adjust the demo though. I would like to keep it as simple as possible. Thank you for the contribution! :)

**Comment by thuytrinh** [comment]
@tokudu Done removing. Need to squash commits?

**Comment by thuytrinh** [comment]
Probably no need to squash. Seems good to go now. After merging ```upstream/master``` into my local branch, I couldn't manage to squash following commits into a single one anymore. Just ended up conflicts.

 ```
5ef13e9 Merge branch 'master' into feature/left_top_margin
f58ea63 Revert "Adjust demo layout to showcase the feature"
e56294b Merge pull request #413 from thuytrinh/feature/margin_top
b517119 Merge pull request #416 from hannesa2/VariablePanelHeigth
41cae7a Adjust demo layout to showcase the feature
c64947c Take marginLeft and marginRight into account for main view
```

**Comment by tokudu** [comment]
LGTM!

**Pull request merged**
